FROM golang:1.11-alpine AS builder
RUN apk add git
RUN mkdir /build
WORKDIR /build
COPY . .
RUN GO111MODULE=on go mod download
RUN CGO_ENABLED=0 go build -o /api ./cmd/api/main.go

# Final image
FROM scratch AS final
COPY --from=builder /api /api
EXPOSE 8080
ENTRYPOINT ["/api"]
